### ISSUE TITLE
Logging: Successful migrations run

### ISSUE THREAD

**Issue by Cactucs** [contember/contember#105]
Currently when server is running content migrations following output is produced:
```
api_1      |   Executing project migrations
api_1      |     Reading migrations from directory "/src/projects/gov/api/migrations"
api_1      |     Executing migration 2020-10-14-102153
```

But there is easy no way to tell¹, that the migration was completed successfully. I would like to see something on the lines of `Migration 2020-10-14-102153 completed`. 

_¹ You may argue that in case of error, the error message is printed, but I don't think this is sufficient, since it is easy to miss or when the migration might be stuck for some time._

**Comment by matej21** [comment]
i will probably rework whole startup output to be less verbose

**Comment by matej21** [comment]
solved in https://github.com/contember/contember/commit/017d4fc29fd3536d9fecaf00db981e2ef02f3809#diff-c67f8155514d4689aeb387f1ba02bf9552250751e3b55144c26281fd944cf12aR81
