### ISSUE TITLE
process.getuid() is not available on Windows

### ISSUE THREAD

**Issue by mjomble** [contember/contember#150]
I tried the [getting started guide](https://www.contember.com/docs/intro/getting-started) on Windows 10 and the command `npx contember instance:up` failed with

```
TypeError: process.getuid is not a function
    at Object.exports.patchInstanceOverrideConfig (...\@contember\cli\src\utils\instance\dockerComposeConfig.ts:138:55)
...
```

**Comment by Cactucs** [comment]
Thanks for the bug report. Windows support can be buggy since none of our developers use them directly, but we will try to improve it. In case you want to try contember out, you can do it using Windows Subsystem for Linux 2 which is much more well-tested.
