### ISSUE TITLE
Instance name requirements

### ISSUE THREAD

**Issue by michalhosna** [contember/contember#32]
When trying to create a new instance 

```
contember instance:create fooBar
```

one gets an error 

```
Invalid instance name. It can contain only alphanumeric letters and cannot start with a number
```

which is clearly not correct as `fooBar` consists solely of alphanumeric characters.

The message should be clearer so one does not have to dig through the code.
https://github.com/contember/contember/blob/aa4fd2ccfa62eedb5518946caaa45e0b50e4191e/packages/cli/src/utils/instance/common.ts#L10-L12

(P.S. alphanumerics are characters not letters)

**Comment by michalhosna** [comment]
Also, why are the requirements so strict? IMHO with this requirements, there is no clear way to separate words in multi-word instance name.

**Comment by matej21** [comment]
This really looks too strict. I guess we can allow uppercase characters.

**Comment by matej21** [comment]
fixed https://github.com/contember/contember/commit/a79357b8dab752a3b3c018cb5d1a755cc89c67f7
