### ISSUE TITLE
Deploy always cannot determine project name

### ISSUE THREAD

**Issue by iBobik** [contember/contember#422]
```
# contember deploy ${{ secrets.CONTEMBER_DSN }}
Please specify a local name project
# contember deploy ${{ secrets.CONTEMBER_DSN }} exampleproject
Project exampleproject not found. Known projects: src
```

Using image [1.3.0-alpha.6](https://hub.docker.com/layers/contember/cli/1.3.0-alpha.6/images/sha256-766c7d10e2d28b6a9a09f976ef2d002c4435d09809d227cc16aa71449e6762e5?context=explore) (btw latest should target to a stable, not alpha version).
Version 1.1.2 works.

**Comment by matej21** [comment]
This was imho same issue as described in #477, right?

**Comment by matej21** [comment]
Multi-project support in CLI is dropped in Contember 2.0, so this is no longer relevant.
