### ISSUE TITLE
Deleting a single entity from several places simultaneously

### ISSUE THREAD

**Issue by JirkaVebr** [contember/contember#51]
A single entity could feasibly appear several times at various places in the tree (e.g. if one's sibling is simultaneously their best friend). Should the client generate a mutation that attempts to delete the entity from each relation (via `delete: true` or `delete: {by "…"}`), the API would fail. This should be a supported use case.

**Comment by matej21** [comment]
solved in cfa21b28e7fed049e2fd2a1fde6e5016a1df3e6e
