### ISSUE TITLE
Support npm workspaces in CLI

### ISSUE THREAD

**Issue by iBobik** [contember/contember#574]
I organize monorepo by npm workspaces which does not create package-lock.json in the subprojects, but [Contember CLI requires it](https://github.com/contember/contember/blob/dabac11e9c2e6eb95d88433c56cad1776e816436/packages/cli-common/src/npm/PackageWorkspaceResolver.ts#L28).

```
> npm run contember --workspace=api migrations:diff init

> @example/api@0.0.0 contember
> docker compose run --rm contember-cli migrations:diff init

[+] Creating 2/0
 ✔ Container example-postgres-1          Running                                                                   0.0s 
 ✔ Container example-contember-engine-1  Running                                                                   0.0s 
[+] Running 1/1
 ✔ Container example-postgres-1  Healthy                                                                           0.5s 
No lockfile found. Please install dependencies using package manager of your choice.
npm error Lifecycle script `contember` failed with error:
npm error code 2
npm error path /example/api
npm error workspace @ example/api@0.0.0
npm error location /example/api
npm error command failed
npm error command sh -c docker compose run --rm contember-cli migrations:diff init
```

**Comment by matej21** [comment]
Hi! 

It looks like the issue might be related to the directory structure or how the `docker-compose` setup is configured. Here are a few things to check:

1. **Directory Structure:** Can you share how your monorepo is organized? The Contember CLI should be able to find a `package-lock.json` file recursively in the parent directories, so even if it's not located directly in the subproject (e.g., `api` workspace), it should still work if the `package-lock.json` exists in the root of your project.

2. **Docker-Compose Volumes:** In your `docker-compose.yml` for the Contember CLI, make sure the volume mounts the root of your monorepo, and not just the subdirectory (e.g., `api`). This way, the CLI can correctly access the `package-lock.json` in the parent directory. You should also set the `working_dir` for the Contember CLI service to point to the right directory.

**Comment by iBobik** [comment]
Hi, thank you for help.

`working_dir` was the key in my case:
```
services:
  contember-cli:
    volumes:
      - ../:/src
    working_dir: '/src/api'
```
for directory structure:
- api
  - package.json
  - docker-compose.yml
- admin
  - package.json
- node_modules
- package.json
- package-lock-json
