### ISSUE TITLE
When migrations genearation fails cli exits with error code 0

### ISSUE THREAD

**Issue by michalhosna** [contember/contember#67]
When one tries to generate migrations for invalid schema, cli reports error `updated schema is not valid` but exists with exit code 0. It should exit with non-zero code.

```
❯ contember migrations:diff foo bar

Project foo:
  updated schema is not valid
     ....
```

Cli version `v0.8.0-alpha.5` (Also, does cli has a command to print versions?).

**Comment by matej21** [comment]
solved 2d199b896c646d83814070e4de75b29878f0dec8
