### ISSUE TITLE
☂️ Content schema endpoint desiderata

### ISSUE THREAD

**Issue by JirkaVebr** [contember/contember#92]
This is an umbrella issue that compiles a list of proposed enhancements of the content schema endpoint just so that it's written down somewhere.

- [ ] **Relation targets**. Which entity is being referenced?
- [ ] **Owning vs inversed side**. While `oneHasMany` is always inversed and `manyHasOne` is always owning (right?), for `oneHasOne` and `manyHasMany` it can go either way. This information should be available.
- [ ] **Enum field types**. In the GraphQL schema the `type` field is a `String!` even though it's really the `Model.ColumnType` enum. I would prefer a GraphQL enum as a sanity check. That said, I'm not sure how that ties in with #69; maybe a `String!` will be necessary after all.
- [ ] **Expose column properties/constraints**. Right now, nullability is only apparent from validation rules. That and perhaps other properties/constraints such as default order, default value, uniqueness, on delete behavior, etc. should be provided explicitly.

**Comment by matej21** [comment]
solved in #112
